services:
  api:
    build: ./api
    restart: always
    # Порты можно не пробрасывать наружу, если к API обращается только бот
    ports:
      - "8000:8000"

  bot:
    build: ./bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot:/app  # Монтируем всю папку бота в папку /app контейнера
    depends_on:
      - api
